{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "wordwall.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordwall.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.istio.gateway }}
  hosts:
  - {{ include "wordwall.name" . }}.sbx.suraj.com
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "wordwall.name" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
