# optional: defaults to the Helm release name when unset
name: ""

namespace: "playground"

backstage:
  component: "httpbin"

image:
  repository: ghcr.io/surajnarwade/wordwall
  tag: sha-5a13579
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8000

probes:
  path: /health
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

istio:
  gateway: istio-ingress/public

serviceAccountName: default

authorizationPolicy:
  enabled: false

virtualService:
  enabled: false
